### ISSUE TITLE
升级open beta4 后短信识别不能用了

### ISSUE THREAD

**Issue by zhanghaocars** [ttimasdf/OnePlusExtension#7]

**Comment by ttimasdf** [comment]
机型？系统？OPMms.apk？

**Comment by zhanghaocars** [comment]
5T，open beta4。重新刷的机，系统里面没有opmms.apk。只有opmmslocation.apk

**Comment by snipking** [comment]
5T，open beta 5 同问题，且现在开启短信识别后短信收不到了，流量校正也用不了了，打开设置中的数据流量直接闪退

以下是提取的 OPMms

[OPMms.apk.zip](https://github.com/ttimasdf/OnePlusExtension/files/1859836/OPMms.apk.zip)

**Comment by ttimasdf** [comment]
我看了一眼代码没啥变化……版本号从1.x变到2.x了，多出来的短信分类也应该hook到了。所以我也不知道咋回事了……

我打包了个debug版，多了一些被屏蔽掉的log消息在 `Mms-debug` 标签下，`Mms` 和 `Xposed` 标签也会有调试日志，试试看有什么东西吧 😺 

数据流量似乎整合到 `com.oneplus.security` 包里了。原来的流量宝 SDK 在我的系统里也没有了。 OP3/OB30

[app-debug.zip](https://github.com/ttimasdf/OnePlusExtension/files/1860770/app-debug.zip)

**Comment by snipking** [comment]
@ttimasdf 

依然收不到短信 & 打开数据流量闪退，错误栈相同如下

```
java.lang.NoSuchFieldError: java.lang.String#DEBUG_ONEPLUS
	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:116)
	at de.robv.android.xposed.XposedHelpers.setBooleanField(XposedHelpers.java:789)
	at pw.rabit.xposed.oneplusextension.OpFeaturesHook.handleLoadPackage(OpFeaturesHook.java:100)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
	at android.app.ActivityThread.handleBindApplication(<Xposed>)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
```

**Comment by ttimasdf** [comment]
这个是我新写的bug没有修复任何老bug 😂 不要在意。这个bug本来应该打开更多调试日志来着。找不到的话就是日志被系统屏蔽了打不开了。

建议你捕捉打开报错页面瞬间的日志，看看是哪个Activity崩掉了或者哪个方法报错。我现在在用氢OS没有什么发言权……

**Comment by snipking** [comment]
可以在 README.md 里面补充一下 How to build 吗？我来改代码改好了给你提 MR 吧

**Comment by ttimasdf** [comment]
非常感谢～
我印象里直接丢进 Android Studio 应该就可以了，你看看不行的话我就写个说明

Sent from Outlook for Android

________________________________
